//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoLib.Domian.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desctiption
    {
        public int Film_Id { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.TimeSpan> TimeDuration { get; set; }
        public string Text { get; set; }
        public int Country_id { get; set; }
        public int Genre_Id { get; set; }
        public int Company_Id { get; set; }
    
        public virtual Company company { get; set; }
        public virtual Country country { get; set; }
        public virtual Film film { get; set; }
        public virtual Genre genre { get; set; }
    }
}
