//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoLib.Domian.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int User_Id { get; set; }
        public int Film_Id { get; set; }
        public Nullable<System.DateTime> DownloadTime { get; set; }
    
        public virtual Film film { get; set; }
        public virtual users users { get; set; }
    }
}
