//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoLib.Domian.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducerStaff
    {
        public int Film_Id { get; set; }
        public string director { get; set; }
        public string producer { get; set; }
        public string @operator { get; set; }
        public string composer { get; set; }
        public string painter { get; set; }
    
        public virtual Film film { get; set; }
    }
}
