//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoLib.Domian.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class userroles
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }
    
        public virtual users users { get; set; }
        public virtual roles roles { get; set; }
    }
}
