//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoLib.Domian.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.favoritefilms = new HashSet<FavoriteFilm>();
            this.userclaims = new HashSet<userclaims>();
            this.userlogins = new HashSet<userlogins>();
            this.roles = new HashSet<roles>();
            this.download = new HashSet<Download>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<FavoriteFilm> favoritefilms { get; set; }
        public virtual ICollection<userclaims> userclaims { get; set; }
        public virtual ICollection<userlogins> userlogins { get; set; }
        public virtual ICollection<roles> roles { get; set; }
        public virtual ICollection<Download> download { get; set; }
    }
}
