//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoLib.Domian.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoLibMainContext : DbContext
    {
        public VideoLibMainContext()
            : base("name=VideoLibMainContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<FavoriteFilm> FavoriteFilms { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<userclaims> userclaims { get; set; }
        public virtual DbSet<userlogins> userlogins { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<Download> Downloads { get; set; }
        public virtual DbSet<Desctiption> Desctiption { get; set; }
        public virtual DbSet<ProducerStaff> ProducerStaff { get; set; }
        public virtual DbSet<AdditionData> AdditionData { get; set; }
    }
}
